name: "Send the Deployment Metadata to API"
description: "Send deployment data to a specified API."
inputs:
  cdp_actions_api_token:
    description: "The API token for authentication"
    required: true
  cdp_server_api_url:
    description: "The base URL for the API server"
    required: true
  deployment_batch_data:
    description: "The deployment batch data in YAML format"
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse YAML and send deployment to API
      shell: bash
      run: |
        # 使用 yq 等工具来解析yaml格式
        deployment_batch_json=$(echo "${{ inputs.deployment_batch_data }}" | yq eval -o=json -)

        # 将 github.run_id 注入 deployment 数据
        deployment_batch_json=$(echo "$deployment_batch_json" | jq '.[] |= . + { "workflowRunId": "'${{ github.run_id }}'" }')

        curl --retry 6 --retry-delay 10 --max-time 10 -X POST "https://cdp-next-test.vercel.app/api/v1/deployments" \
        -H "Content-Type: application/json" \
        -H "CDP-Actions-API-Token: Bearer ${{ inputs.cdp_actions_api_token }}" \
        -d "$deployment_batch_json"