name: Upload Metadata to API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 加载环境变量
        run: |
          echo "当前目录: $(pwd)"  # 查看当前目录
          ls -al                  # 列出文件
          if [ -f .env ]; then    # 在当前目录查找 .env 文件
            echo ".env 文件内容:"
            cat .env              # 输出 .env 文件内容以确保其被找到
            # 将环境变量加载到 $GITHUB_ENV
            while IFS= read -r line || [[ -n "$line" ]]; do
              echo "$line" >> $GITHUB_ENV
            done < .env
          else
            echo ".env 文件未找到！"
          fi

      - name: 打印环境变量
        run: |
          echo "API Token: $API_TOKEN"
          echo "Environment: $ENVIRONMENT"

      - name: 发送元数据到 API
        run: |
          curl -X POST https://internal-developer-platform-demo.edanliu.workers.dev/metadata \
          -H "Content-Type: application/json" \
          -d @- <<EOF
          {
            "workflowName": "${GITHUB_WORKFLOW}",
            "status": "success",
            "jobId": "${GITHUB_JOB}",
            "runId": "${GITHUB_RUN_ID}",
            "repository": "${GITHUB_REPOSITORY}",
            "apiToken": "${API_TOKEN}",
            "environment": "${ENVIRONMENT}"
          }
          EOF