name: Upload Deployment Batch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send deployment to API
        uses: EdanXmind/test-bot/deployments@main
        with:
          cdp_actions_api_token: ${{ secrets.CDP_ACTIONS_API_TOKEN }}
          cdp_server_api_url: ${{ vars.CDP_SERVER_API_URL }}
          deployment_batch_data: |
            - artifactName: "test-action-artifact"
              artifactVersion: "1.0.0"
              componentName: "test-1-1"
              componentType: "yml"
              env:
                - "development"
                - "test"
              workflowRunId: "${{ github.run_id }}"
            - artifactName: "test-action-artifact"
              artifactVersion: "1.0.0"
              componentName: "test-2"
              componentType: "text"
              env:
                - "production"