name: Upload Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send artifact metadata to CDP
        uses: EdanXmind/test-bot/artifacts@main
        with:
          cdp_actions_api_token: ${{ secrets.CDP_ACTIONS_API_TOKEN }}
          name: "s3://xxx/applications/"
          version: "1.1.1"
          type: "s3-uri"
          tags: '{"feat_open": true, "priority": 29, "pm": "jack", "canary_user": [2, 3, 111, 34], "abc:ui:nn": true}'

      - name: Send artifact metadata to CDP
        uses: EdanXmind/test-bot/artifacts@main
        with:
          cdp_actions_api_token: ${{ secrets.CDP_ACTIONS_API_TOKEN }}
          name: "s3://yyy/applications/"
          version: "1.0.0"
          type: "s3-uri"

      - name: Send deployment to API
        uses: EdanXmind/test-bot/deployments@main
        with:
          cdp_actions_api_token: ${{ secrets.CDP_ACTIONS_API_TOKEN }}
          cdp_server_api_url: ${{ vars.CDP_SERVER_API_URL }}
          deployment_batch_data: |
            - artifactName: "test-action-artifact"
              artifactVersion: "1.0.0"
              componentName: "test-1-1"
              componentType: "yml"
              env:
                - "development"
                - "test"
            - artifactName: "test-action-artifact"
              artifactVersion: "1.0.0"
              componentName: "test-2"
              componentType: "text"
              env:
                - "production"    
