name: Upload Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send artifact metadata to CDP
        uses: EdanXmind/test-bot/artifacts@main
        with:
          cdp_actions_api_token: ${{ secrets.CDP_ACTIONS_API_TOKEN }}
          name: "s3://xxx/applications/"
          version: "1.1.1"
          type: "s3-uri"
          tag: [{"feat_open": true}, {"test": "test"}]

      - name: Send artifact metadata to CDP
        uses: EdanXmind/test-bot/artifacts@main
        with:
          cdp_actions_api_token: ${{ secrets.CDP_ACTIONS_API_TOKEN }}
          name: "s3://yyy/applications/"
          version: "1.0.0"
          type: "s3-uri"
