name: 'Upload Artifact'
description: 'Send artifact data to a specified API.'

inputs:
  cdp_actions_api_token:
    description: 'The API token for authentication'
    required: true
  name:
    description: 'Artifact name'
    required: false
    default: null
  version:
    description: 'Artifact version'
    required: false
    default: null
  size_kb:
    description: 'Size of the artifact in KB'
    required: false
    default: '0'
  env:
    description: 'Environment for the artifact'
    required: false
    default: null
  type:
    description: 'Artifact type'
    required: false
    default: null
  tags:
    description: 'Custom tags in JSON format'
    required: false
    default: '{}'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload the Artifact Metadata using JavaScript
      run: |
        node ./artifacts/index.js
      shell: bash
      env:
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        INPUT_CDP_ACTIONS_API_TOKEN: ${{ inputs.cdp_actions_api_token }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_SIZE_KB: ${{ inputs.size_kb }}
        INPUT_ENV: ${{ inputs.env }}
        INPUT_TYPE: ${{ inputs.type }}
        INPUT_TAGS: ${{ inputs.tags }}
