name: "Upload Artifact"
description: "Send artifact data to a specified API."
inputs:
  cdp_actions_api_token:
    description: "The API token for authentication"
    required: true
  name:
    description: "Artifact name"
    required: false
    default: null
  version:
    description: "Artifact version"
    required: false
    default: null
  size_kb:
    description: "Size of the artifact in KB"
    required: false
    default: "0"
  env:
    description: "Environment for the artifact"
    required: false
    default: null
  type:
    description: "Artifact type"
    required: false
    default: null
  tags:
    description: "Custom tags in JSON format"
    required: false
    default: null

runs:
  using: "composite"
  steps:
    - name: Upload the Artifact Metadata
      shell: bash
      run: |
        curl --retry 6 --retry-delay 10 --max-time 10 -X POST "https://cdp-next-test.vercel.app/api/v1/artifacts" \
        -H "Content-Type: application/json" \
        -H "CDP-Actions-API-Token: Bearer ${{ inputs.cdp_actions_api_token }}" \
        -d @- <<EOF
        {
          "name": "${{ inputs.name }}",
          "version": "${{ inputs.version }}",
          "sizeKb": ${{ inputs.size_kb }},
          "env": "${{ inputs.env }}",
          "type": "${{ inputs.type }}",
          "codebaseCommit": "${{ github.sha }}",
          "repoBranch": "${{ github.ref_name }}",
          "workflowTitle": "${{ github.workflow }}",
          "workflowUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          "workflowRunId": "${{ github.run_id }}",
          "githubRepoName": "${{ github.repository }}",
          "tags": ${{ inputs.tags || '[]' }}
        }
        EOF
